# Generated by Django 3.0.5 on 2020-04-14 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artists', '0003_auto_20200309_1032'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('artist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artist_lot', to='artists.Artists')),
            ],
        ),
    ]
