# Generated by Django 3.0.5 on 2020-04-14 09:35

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appraisers', '0004_auto_20200309_1700'),
        ('customers', '0001_initial'),
        ('lots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lots',
            name='appraiser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appraiser_lot', to='appraisers.Appraisers'),
        ),
        migrations.AddField(
            model_name='lots',
            name='code',
            field=models.PositiveIntegerField(null=True, unique=True, validators=[django.core.validators.MinValueValidator(600000)]),
        ),
        migrations.AddField(
            model_name='lots',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lots',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lot_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lots',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_lot', to='customers.Customer'),
        ),
        migrations.AddField(
            model_name='lots',
            name='desc',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lots',
            name='modifier',
            field=models.ForeignKey(null=True, on_delete=models.SET('1'), related_name='lot_modifier', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lots',
            name='modify_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='lots',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='lots',
            name='worknumber',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
