# Generated by Django 3.0.5 on 2020-04-19 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('technics', '0005_auto_20200309_1105'),
        ('lots', '0002_auto_20200414_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='lots',
            name='technic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='technic_lot', to='technics.Technics'),
        ),
    ]
