# Generated by Django 3.0.5 on 2020-04-19 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0003_lots_technic'),
    ]

    operations = [
        migrations.AddField(
            model_name='lots',
            name='size',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='lots',
            name='type',
            field=models.CharField(blank=True, choices=[('B', 'Bútor'), ('M', 'Műtárgy'), ('S', 'Szőnyeg'), ('E', 'Ezüst'), ('K', 'Ékszer')], default=None, max_length=128),
        ),
    ]
