# Generated by Django 3.0.5 on 2020-04-19 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0005_auto_20200419_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lots',
            name='type',
            field=models.CharField(blank=True, choices=[('B', 'Bútor'), ('M', 'Műtárgy'), ('S', 'Szőnyeg'), ('E', 'Ezüst'), ('K', 'Ékszer'), ('O', 'Szobor'), ('F', 'Festmény'), ('G', 'Grafika')], default=None, max_length=128),
        ),
    ]
