# Generated by Django 3.0.5 on 2020-04-19 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0006_auto_20200419_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='lots',
            name='purchase',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
