# Generated by Django 3.0.5 on 2020-04-19 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0008_auto_20200419_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lots',
            name='limit',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='lots',
            name='pay',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='lots',
            name='price',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='lots',
            name='purchase',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='lots',
            name='start',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
