# Generated by Django 3.0.5 on 2020-04-19 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0009_auto_20200419_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='lots',
            name='note',
            field=models.TextField(blank=True),
        ),
    ]
