# Generated by Django 3.0.5 on 2020-04-19 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0010_lots_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='lots',
            name='weight',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
