# Generated by Django 3.0.5 on 2020-04-25 15:20

import django.core.validators
from django.db import migrations, models
import lots.models


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0011_lots_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='lots',
            name='photo',
            field=models.ImageField(default='images/default.jpg', upload_to=lots.models.path_and_rename),
        ),
        migrations.AlterField(
            model_name='lots',
            name='code',
            field=models.PositiveIntegerField(null=True, unique=True, validators=[django.core.validators.MinValueValidator(600000), django.core.validators.MaxValueValidator(699999)]),
        ),
        migrations.AlterField(
            model_name='lots',
            name='type',
            field=models.CharField(choices=[('', '---------'), ('B', 'Bútor'), ('M', 'Műtárgy'), ('S', 'Szőnyeg'), ('E', 'Ezüst'), ('K', 'Ékszer'), ('O', 'Szobor'), ('F', 'Festmény'), ('G', 'Grafika')], default=None, max_length=128, validators=[lots.models.validate_type]),
        ),
    ]
