# Generated by Django 3.0.5 on 2020-04-25 15:35

from django.db import migrations, models
import lots.models


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0012_auto_20200425_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lots',
            name='photo',
            field=models.ImageField(default='images/default.png', upload_to=lots.models.path_and_rename),
        ),
    ]
