# Generated by Django 3.0.5 on 2020-04-26 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0013_auto_20200425_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lots',
            name='price',
            field=models.CharField(blank=True, default=0, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='lots',
            name='purchase',
            field=models.CharField(blank=True, default=0, max_length=20, null=True),
        ),
    ]
