# Generated by Django 3.0.5 on 2020-04-26 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0014_auto_20200426_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lots',
            name='limit',
            field=models.CharField(blank=True, default=0, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='lots',
            name='pay',
            field=models.CharField(blank=True, default=0, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='lots',
            name='start',
            field=models.CharField(blank=True, default=0, max_length=20, null=True),
        ),
    ]
