# Generated by Django 3.0.5 on 2020-05-10 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0018_lots_vjegy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lots',
            name='vjegy',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
