# Generated by Django 3.0.5 on 2020-05-14 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0024_auto_20200513_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='lots',
            name='status_sold',
            field=models.BooleanField(default=False),
        ),
    ]
