# Generated by Django 3.0.2 on 2020-02-24 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extra', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extras',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
