# Generated by Django 3.0.3 on 2020-03-01 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appraisers', '0001_initial'),
        ('extra', '0002_auto_20200224_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='extras',
            name='appraiser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appraiser_extra', to='appraisers.Appraisers'),
        ),
    ]
