# Generated by Django 3.0.2 on 2020-03-02 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('technics', '0002_auto_20200302_0927'),
        ('extra', '0003_extras_appraiser'),
    ]

    operations = [
        migrations.AddField(
            model_name='extras',
            name='technic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='technic_extra', to='technics.Technics'),
        ),
    ]
