# Generated by Django 3.0.2 on 2020-03-09 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extra', '0004_extras_technic'),
    ]

    operations = [
        migrations.AddField(
            model_name='extras',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
