# Generated by Django 3.0.2 on 2020-03-09 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extra', '0005_extras_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='extras',
            name='worknumber',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
