# Generated by Django 3.0.2 on 2020-03-09 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extra', '0007_auto_20200309_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extras',
            name='worknumber',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
