# Generated by Django 3.0.2 on 2020-03-09 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extra', '0008_auto_20200309_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extras',
            name='worknumber',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
