# Generated by Django 3.0.2 on 2020-03-10 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0003_auto_20200309_1032'),
        ('extra', '0012_auto_20200309_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extras',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artist_extra', to='artists.Artists'),
        ),
        migrations.AlterField(
            model_name='extras',
            name='worknumber',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
