# Generated by Django 3.0.2 on 2020-03-02 08:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('technics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technics',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET('1'), related_name='technic_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='technics',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=models.SET('1'), related_name='technic_modifier', to=settings.AUTH_USER_MODEL),
        ),
    ]
