# Generated by Django 3.0.3 on 2020-02-23 09:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('technics', '0002_auto_20200114_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='technics',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET('1'), related_name='created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='technics',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=models.SET('1'), related_name='modified', to=settings.AUTH_USER_MODEL),
        ),
    ]
