# Generated by Django 3.0.2 on 2020-03-09 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technics', '0003_auto_20200309_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technics',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
