# Generated by Django 3.0.2 on 2020-03-09 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technics', '0004_auto_20200309_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technics',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
