# Generated by Django 3.0.5 on 2020-04-17 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20200417_2225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='modified_by',
            new_name='modifier',
        ),
    ]
