# Generated by Django 3.0.2 on 2020-01-11 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20200111_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='bank',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
