# Generated by Django 3.0.2 on 2020-01-11 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_customer_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='taxnumber',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
