# Generated by Django 3.0.2 on 2020-03-09 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisers', '0002_auto_20200309_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appraisers',
            name='name',
            field=models.CharField(default='none', max_length=120),
        ),
    ]
