# Generated by Django 3.0.5 on 2020-05-07 14:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lots', '0017_auto_20200506_1802'),
        ('customers', '0003_auto_20200417_2229'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sold', models.CharField(blank=True, max_length=20, null=True)),
                ('invoice', models.CharField(blank=True, max_length=255)),
                ('customer_invoice', models.CharField(blank=True, max_length=255)),
                ('sale_date', models.DateField(null=True)),
                ('note', models.TextField(blank=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('modify_date', models.DateTimeField(auto_now=True)),
                ('code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_lot', to='lots.Lots')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sale_creator', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_customer', to='customers.Customer')),
                ('modifier', models.ForeignKey(null=True, on_delete=models.SET('1'), related_name='sale_modifier', to=settings.AUTH_USER_MODEL)),
                ('pay', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_pay', to='lots.Lots')),
                ('purchase', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_purchase', to='lots.Lots')),
                ('vjegy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_vjegy', to='lots.Lots')),
            ],
        ),
    ]
