# Generated by Django 3.0.5 on 2020-05-07 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0018_lots_vjegy'),
        ('sale', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_lot', to='lots.Lots', to_field='code'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='pay',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='purchase',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='sold',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='vjegy',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
