# Generated by Django 3.0.5 on 2020-05-11 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='diff',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sales',
            name='tax',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
