# Generated by Django 3.0.5 on 2020-05-07 17:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0002_auto_20200507_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, unique=True),
            preserve_default=False,
        ),
    ]
