# Generated by Django 3.0.5 on 2020-05-09 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_auto_20200417_2229'),
        ('sale', '0003_sales_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='customer',
        ),
        migrations.AddField(
            model_name='sales',
            name='buyer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_buyer', to='customers.Customer'),
        ),
    ]
