# Generated by Django 3.0.5 on 2020-05-12 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0003_auto_20200512_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='sold',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
