# Generated by Django 3.0.5 on 2020-05-12 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0005_auto_20200512_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='pay',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
