# Generated by Django 3.0.5 on 2020-05-13 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0006_auto_20200512_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='purchase',
            field=models.IntegerField(null=True),
        ),
    ]
